//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuetzalExpress.ConexionWeb {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConexionWeb.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Guardar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Guardar(string nombre, string apellido, int dpi, int nit, int telefono, string direccion, string email, string fecnac, int numtar, string tiptar, string fecex, string banco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CargarClientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CargarClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CargarDatos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CargarDatos(string datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoguinCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LoguinCliente(string Usuario, string Contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Loguin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Loguin(string Usuario, string Contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoguinPass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LoguinPass(string Usuario, string Contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarCategoria", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string insertarCategoria(string nombre, int impuesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarPaquete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool insertarPaquete(string clasificacion, string descripcion, string peso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCodigoPaquete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string obtenerCodigoPaquete();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCodigoDetallePaquete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string obtenerCodigoDetallePaquete();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCodigoCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string obtenerCodigoCliente(string casilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarPaquete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool registrarPaquete(string clasificacion, string descripcion, string peso, string destino, string codCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarDetallePaquete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ingresarDetallePaquete(string destino, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarCodigoDetallePaquete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ingresarCodigoDetallePaquete(string codigoDetalle);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : QuetzalExpress.ConexionWeb.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<QuetzalExpress.ConexionWeb.ServiceSoap>, QuetzalExpress.ConexionWeb.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public bool Guardar(string nombre, string apellido, int dpi, int nit, int telefono, string direccion, string email, string fecnac, int numtar, string tiptar, string fecex, string banco) {
            return base.Channel.Guardar(nombre, apellido, dpi, nit, telefono, direccion, email, fecnac, numtar, tiptar, fecex, banco);
        }
        
        public System.Data.DataSet CargarClientes() {
            return base.Channel.CargarClientes();
        }
        
        public bool CargarDatos(string datos) {
            return base.Channel.CargarDatos(datos);
        }
        
        public string LoguinCliente(string Usuario, string Contrasena) {
            return base.Channel.LoguinCliente(Usuario, Contrasena);
        }
        
        public string Loguin(string Usuario, string Contrasena) {
            return base.Channel.Loguin(Usuario, Contrasena);
        }
        
        public string LoguinPass(string Usuario, string Contrasena) {
            return base.Channel.LoguinPass(Usuario, Contrasena);
        }
        
        public string insertarCategoria(string nombre, int impuesto) {
            return base.Channel.insertarCategoria(nombre, impuesto);
        }
        
        public bool insertarPaquete(string clasificacion, string descripcion, string peso) {
            return base.Channel.insertarPaquete(clasificacion, descripcion, peso);
        }
        
        public string obtenerCodigoPaquete() {
            return base.Channel.obtenerCodigoPaquete();
        }
        
        public string obtenerCodigoDetallePaquete() {
            return base.Channel.obtenerCodigoDetallePaquete();
        }
        
        public string obtenerCodigoCliente(string casilla) {
            return base.Channel.obtenerCodigoCliente(casilla);
        }
        
        public bool registrarPaquete(string clasificacion, string descripcion, string peso, string destino, string codCliente) {
            return base.Channel.registrarPaquete(clasificacion, descripcion, peso, destino, codCliente);
        }
        
        public bool ingresarDetallePaquete(string destino, string codigo) {
            return base.Channel.ingresarDetallePaquete(destino, codigo);
        }
        
        public bool ingresarCodigoDetallePaquete(string codigoDetalle) {
            return base.Channel.ingresarCodigoDetallePaquete(codigoDetalle);
        }
    }
}
